import re

replacements = {
    "reviewhubpage-style-1": "flex-1 overflow-hidden w-full h-full flex flex-col box-border pt-5 px-8 pb-4 bg-slate-50 dark:bg-slate-950",
    "reviewhubpage-style-2": "max-w-[1100px] w-full mx-auto flex flex-col flex-1 min-h-0 gap-4",
    "reviewhubpage-style-3": "flex items-center justify-between shrink-0",
    "reviewhubpage-style-4": "flex items-center gap-6",
    "reviewhubpage-style-5": "text-[22px] font-extrabold m-0 tracking-[-0.3px] text-slate-900 dark:text-slate-100",
    "reviewhubpage-style-6": "inline-flex items-center gap-2.5 px-4 py-[7px] rounded-full border-[1.5px] border-emerald-500/25 bg-emerald-500/10 text-emerald-600 dark:text-emerald-500 text-[13px] font-bold",
    "reviewhubpage-style-7": "relative flex w-2 h-2",
    "reviewhubpage-style-8": "absolute top-0 left-0 w-full h-full rounded-full bg-emerald-500 opacity-75 animate-[ping_1.2s_cubic-bezier(0,0,0.2,1)_infinite]",
    "reviewhubpage-style-9": "relative block w-2 h-2 rounded-full bg-emerald-500",
    "reviewhubpage-style-10": "inline-flex items-center gap-2 px-3.5 py-[7px] rounded-full border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 text-[13px] font-semibold",
    "reviewhubpage-style-11": "text-emerald-500",
    "reviewhubpage-style-12": "mb-5",
    "reviewhubpage-style-13": "flex items-center gap-2.5 mb-3",
    "reviewhubpage-style-14": "w-1 h-3.5 bg-emerald-500 rounded",
    "reviewhubpage-style-15": "text-[13px] font-bold uppercase tracking-[0.05em] m-0 text-slate-900 dark:text-slate-100",
    "reviewhubpage-style-16": "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 flex flex-col relative overflow-visible",
    "reviewhubpage-style-17": "flex items-center justify-between gap-4 z-10 flex-wrap",
    "reviewhubpage-style-18": "flex gap-4 items-center",
    "reviewhubpage-style-19": "w-[52px] h-[52px] rounded-[14px] bg-emerald-500/10 flex items-center justify-center text-emerald-500 shrink-0",
    "reviewhubpage-style-20": "flex items-center gap-2 mb-1",
    "reviewhubpage-style-21": "text-lg font-extrabold m-0 text-slate-900 dark:text-slate-100",
    "reviewhubpage-style-22": "text-[10px] font-bold text-emerald-600 dark:text-emerald-500 bg-emerald-500/15 px-1.5 py-[3px] rounded-md uppercase tracking-[0.05em]",
    "reviewhubpage-style-23": "text-[13px] text-slate-500 dark:text-slate-400 leading-relaxed m-0 max-w-[500px]",
    "reviewhubpage-style-24": "mt-2.5 relative",
    "reviewhubpage-style-25": "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[11px] font-semibold cursor-pointer",
    "reviewhubpage-style-26": "absolute top-full left-0 z-50 mt-1.5 w-[220px] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[10px] shadow-lg p-2.5 flex flex-col gap-1.5",
    "reviewhubpage-style-27": "text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase",
    "reviewhubpage-style-28": "flex flex-wrap gap-1",
    "reviewhubpage-style-29": "px-2 py-1 rounded-md text-[11px] font-medium cursor-pointer",
    "reviewhubpage-style-30": "mt-1 p-1.5 bg-transparent border-none text-slate-500 dark:text-slate-400 text-[11px] cursor-pointer font-semibold",
    "reviewhubpage-style-31": "flex items-center gap-2 px-6 py-3 rounded-xl border-none font-bold text-sm shrink-0 transition-all duration-200",
    "reviewhubpage-style-32": "flex items-center gap-2.5 mb-3",
    "reviewhubpage-style-33": "w-1 h-3.5 bg-slate-400 dark:bg-slate-600 rounded",
    "reviewhubpage-style-34": "text-[13px] font-bold text-slate-900 dark:text-slate-100 uppercase tracking-[0.05em] m-0",
    "reviewhubpage-style-35": "grid grid-cols-1 md:grid-cols-3 gap-3 flex-1 min-h-0",
    "reviewhubpage-style-36": "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[14px] p-4 flex flex-col gap-2.5 transition-shadow duration-200",
    "reviewhubpage-style-37": "flex justify-between items-start mb-2.5",
    "reviewhubpage-style-38": "flex items-center gap-2",
    "reviewhubpage-style-39": "w-10 h-10 rounded-[10px] bg-blue-500/10 flex items-center justify-center text-blue-500",
    "reviewhubpage-style-40": "text-[10px] font-bold text-blue-500 uppercase tracking-[0.08em]",
    "reviewhubpage-style-41": "text-base font-bold text-slate-900 dark:text-slate-100",
    "reviewhubpage-style-42": "text-slate-500 dark:text-slate-400",
    "reviewhubpage-style-43": "text-[13px] text-slate-500 dark:text-slate-400 leading-relaxed m-0 mb-4",
    "reviewhubpage-style-44": "relative",
    "reviewhubpage-style-45": "w-full flex items-center justify-between px-3.5 py-2.5 rounded-[10px] border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 cursor-pointer text-[13px] font-medium",
    "reviewhubpage-style-46": "overflow-hidden text-ellipsis whitespace-nowrap",
    "reviewhubpage-style-47": "absolute top-full left-0 right-0 z-50 mt-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[10px] overflow-hidden shadow-lg max-h-[220px] overflow-y-auto",
    "reviewhubpage-style-48": "px-3.5 py-2.5 cursor-pointer flex items-center justify-between text-[13px] font-medium text-slate-900 dark:text-slate-100 border-b border-slate-200 dark:border-slate-800 transition-colors duration-100",
    "reviewhubpage-style-49": "overflow-hidden text-ellipsis whitespace-nowrap flex-1",
    "reviewhubpage-style-50": "text-[11px] text-slate-500 dark:text-slate-400 ml-2 shrink-0",
    "reviewhubpage-style-51": "flex items-center justify-center gap-2 px-4 py-3 rounded-[10px] border-none font-bold text-sm transition-all duration-200 mt-auto",
    "reviewhubpage-style-52": "fixed inset-0 z-[1000] flex items-center justify-center",
    "reviewhubpage-style-53": "absolute inset-0 bg-black/60 backdrop-blur-sm",
    "reviewhubpage-style-54": "relative bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-[20px] w-full max-w-[600px] p-8 shadow-xl flex flex-col gap-6 max-h-[90vh] overflow-y-auto",
    "reviewhubpage-style-55": "absolute top-5 right-5 bg-transparent border-none text-slate-500 dark:text-slate-400 cursor-pointer p-2 rounded-full",
    "reviewhubpage-style-56": "text-[22px] font-extrabold text-slate-900 dark:text-slate-100 m-0 mb-2",
    "reviewhubpage-style-57": "m-0 text-sm text-slate-500 dark:text-slate-400",
    "reviewhubpage-style-58": "block text-[13px] font-bold text-slate-900 dark:text-slate-100 uppercase tracking-[0.05em] mb-3",
    "reviewhubpage-style-59": "flex flex-wrap gap-2",
    "reviewhubpage-style-60": "px-4 py-2 rounded-full text-[13px] font-semibold cursor-pointer transition-all duration-200",
    "reviewhubpage-style-61": "block text-[13px] font-bold text-slate-900 dark:text-slate-100 uppercase tracking-[0.05em] mb-3",
    "reviewhubpage-style-62": "text-[13px] text-slate-500 dark:text-slate-400 italic",
    "reviewhubpage-style-63": "flex flex-wrap gap-2 max-h-[150px] overflow-y-auto p-1 -m-1 custom-scrollbar",
    "reviewhubpage-style-64": "px-3 py-1.5 rounded-full text-xs font-semibold cursor-pointer transition-all duration-200 flex items-center gap-1.5",
    "reviewhubpage-style-65": "block text-[13px] font-bold text-slate-900 dark:text-slate-100 uppercase tracking-[0.05em] mb-3",
    "reviewhubpage-style-66": "flex flex-wrap gap-2",
    "reviewhubpage-style-67": "px-4 py-2 rounded-full text-[13px] font-semibold cursor-pointer transition-all duration-200 flex items-center gap-2",
    "reviewhubpage-style-68": "w-2 h-2 rounded-full",
    "reviewhubpage-style-69": "block text-[13px] font-bold text-slate-900 dark:text-slate-100 uppercase tracking-[0.05em] mb-3",
    "reviewhubpage-style-70": "px-3.5 py-2.5 rounded-[10px] border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 text-sm outline-none w-full max-w-[200px]",
    "reviewhubpage-style-71": "mt-2 border-t border-slate-200 dark:border-slate-800 pt-6 flex justify-between items-center gap-3",
    "reviewhubpage-style-72": "text-[0.82rem] text-slate-500 dark:text-slate-400",
    "reviewhubpage-style-73": "text-slate-900 dark:text-slate-100",
    "reviewhubpage-style-74": "text-amber-500",
    "reviewhubpage-style-75": "flex gap-2.5 items-center",
    "reviewhubpage-style-76": "px-4 py-2.5 bg-transparent border-none text-slate-500 dark:text-slate-400 font-semibold text-sm cursor-pointer rounded-[10px]",
    "reviewhubpage-style-77": "px-6 py-2.5 border-none rounded-[10px] font-bold text-sm transition-all duration-150",
    "reviewhubpage-style-78": "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[14px] p-4 flex flex-col gap-2.5 transition-all duration-200 min-h-0 overflow-hidden",
    "reviewhubpage-style-79": "flex items-center justify-between",
    "reviewhubpage-style-80": "flex items-center gap-2.5",
    "reviewhubpage-style-81": "w-[34px] h-[34px] rounded-md flex items-center justify-center shrink-0",
    "reviewhubpage-style-82": "text-[9px] font-bold uppercase tracking-[0.08em] leading-none",
    "reviewhubpage-style-83": "text-sm font-bold text-slate-900 dark:text-slate-100 leading-tight mt-0.5",
    "reviewhubpage-style-84": "text-slate-500 dark:text-slate-400",
    "reviewhubpage-style-85": "text-xs text-slate-500 dark:text-slate-400 leading-relaxed m-0 flex-1 min-h-0 line-clamp-3",
    "reviewhubpage-style-86": "mt-auto flex items-center justify-start",
    "reviewhubpage-style-87": "flex items-center justify-center gap-1.5 py-2 px-0 border-none bg-transparent font-bold text-[13px] transition-colors duration-200 shrink-0",
    "reviewhubpage-style-88": "ml-1",
}

with open("src/components/ReviewHubPage.tsx", "r") as f:
    content = f.read()

for style_id, tailwind_classes in replacements.items():
    content = content.replace(f'className="{style_id}"', f'className="{tailwind_classes}"')
    content = content.replace(f'className="{style_id} ', f'className="{tailwind_classes} ')
    content = content.replace(f' {style_id}"', f' {tailwind_classes}"')
    content = content.replace(f' {style_id} ', f' {tailwind_classes} ')

# Remove the import line
content = content.replace("import './styles/ReviewHubPage.css';\n", "")

with open("src/components/ReviewHubPage.tsx", "w") as f:
    f.write(content)
